# Extração dos Relatórios - ESJs

O objetivo deste código é extrair os relatórios dos textos referentes aos Extratos de Sessões de Julgamento.

Para isso, usaremos os dados que contém os textos dos processos, e faremos uso de expressões regulares para delimitar o início e o fim do relatório.

In [57]:
import os
import pandas as pd
import re
import random
import numpy as np
import time

In [58]:
df = pd.read_csv("D:/Backup Tomas/T0mas/Faculdade/IC/Geral/Github CVM/corporate-fraud-in-brazil/data/interim/textos_dos_processos/textos_esjs.csv")

In [59]:
print(df)

                        ID                                              Texto  \
0               IA-1995-21  Voltar\nSESSÃO DE JULGAMENTO DO\nINQUÉRITO ADM...
1               IA-1996-10  Voltar\nSESSÃO DE JULGAMENTO DO\nINQUÉRITO ADM...
2               IA-1997-12  Voltar\nilde;O DE JULGAMENTO DO\nINQUÉRITO ADM...
3               IA-1998-01  Voltar\nSESSÃO DE JULGAMENTO DO\nINQUÉRITO ADM...
4               IA-1998-05  Voltar\nSESSÃO DE JULGAMENTO DO\nINQUÉRITO ADM...
...                    ...                                                ...
1266  19957-011361-2018-48  Diário Eletrônico da CVM em\n17/07/2023\nCOMIS...
1267  19957-011669-2017-11  Diário Eletrônico da CVM em\n25/10/2023\nCOMIS...
1268  19957-012126-2022-70  Diário Eletrônico da CVM em\n11/08/2023\nCOMIS...
1269  19957-012414-2022-24  Diário Eletrônico da CVM em\n21/08/2023\nCOMIS...
1270  19957-015734-2022-36  Diário Eletrônico da CVM em\n01/11/2023\nCOMIS...

      Escaneado
0         False
1         False
2         False
3         False
4         False
...         ...
1266      False
1267      False
1268      False
1269      False
1270      False

[1271 rows x 3 columns]

In [60]:
def extrair_relatorio(texto):

    # Padrão para pegar "Relatório ... É o relatório"
    pattern_relatorio = r"(RELATÓRIO|Relatório|Relatorio|RELATORIO)(.*?)(É o relatório|(?:Rio de Janeiro|São Paulo), (?:\d{2}|\d{1}) de (?:janeiro|fevereiro|março|abril|maio|junho|julho|agosto|setembro|outubro|novembro|dezembro) de 20\d{2})" #Padrão
    match_relatorio = re.search(pattern_relatorio, texto, flags=re.DOTALL) #Procura pelo padrão

    relatorio = (match_relatorio.group(1) + match_relatorio.group(2) + match_relatorio.group(3)) if match_relatorio else np.nan #Definimos o relatório como a união das três strings.

    return relatorio #Retornamos o número do processo e o relatório.

In [61]:
df['Relatório'] = df['Texto'].apply(extrair_relatorio)

df

,ID,Texto,Escaneado,Relatório
0,IA-1995-21,Voltar\nSESSÃO DE JULGAMENTO DO\nINQUÉRITO ADM...,False,NaN
1,IA-1996-10,Voltar\nSESSÃO DE JULGAMENTO DO\nINQUÉRITO ADM...,False,NaN
2,IA-1997-12,Voltar\nilde;O DE JULGAMENTO DO\nINQUÉRITO ADM...,False,RELATÓRIO\nSenhores Membros do Colegiado:\nO p...
3,IA-1998-01,Voltar\nSESSÃO DE JULGAMENTO DO\nINQUÉRITO ADM...,False,RELATÓRIO\nRELATOR : Diretor Durval José Soled...
4,IA-1998-05,Voltar\nSESSÃO DE JULGAMENTO DO\nINQUÉRITO ADM...,False,RELATÓRIO COMPLEMENTAR\nRelator : Diretor Wlad...
...,...,...,...,...
1266,19957-011361-2018-48,Diário Eletrônico da CVM em\n17/07/2023\nCOMIS...,False,"Relatório, conforme o caso.\n2 O Inquérito Adm..."
1267,19957-011669-2017-11,Diário Eletrônico da CVM em\n25/10/2023\nCOMIS...,False,RELATÓRIO\nI. OBJETO E ORIGEM\n1. Trata-se de ...
1268,19957-012126-2022-70,Diário Eletrônico da CVM em\n11/08/2023\nCOMIS...,False,RELATÓRIO\nI. OBJETO\n1. Trata-se de Processo ...
1269,19957-012414-2022-24,Diário Eletrônico da CVM em\n21/08/2023\nCOMIS...,False,NaN
1270,19957-015734-2022-36,Diário Eletrônico da CVM em\n01/11/2023\nCOMIS...,False,RELATÓRIO DE JULGAMENTO - GAIN\nPROCESSO ADMIN...

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1271 entries, 0 to 1270
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         1271 non-null   object
 1   Texto      1271 non-null   object
 2   Escaneado  1271 non-null   bool
 3   Relatório  1189 non-null   object
dtypes: bool(1), object(3)
memory usage: 31.2+ KB

In [63]:
nulos = df.loc[df['Relatório'].isna(), 'ID'].tolist()
print(nulos)

['IA-1995-21', 'IA-1996-10', 'IA-1998-13', 'IA-1999-08', 'IA-1999-25', 'IA-1998-20', 'RJ-2002-05015', 'RJ-2003-12911', 'RJ-2005-03646', 'SP-2004-00154', 'RJ-2005-02933', 'RJ-2005-03108', 'SP-2003-00205', 'IA-2004-05', 'IA-2004-07', 'SP-2005-00180', 'IA-2006-01', 'RJ-2007-08109', 'IA-2003-20', 'RJ-2007-02078', 'RJ-2007-03673', 'RJ-2007-14153', 'RJ-2008-05752', 'SP-2007-00167', 'RJ-2008-02916', 'RJ-2008-04768', 'RJ-2008-08572', 'RJ-2008-12088', 'RJ-2008-12216', 'RJ-2009-01365', 'RJ-2009-02146', 'RJ-2009-13459', 'RJ-2010-08588', 'IA-2006-10', 'RJ-2010-04206', 'RJ-2010-10528', 'RJ-2010-14407', 'RJ-2011-03262', 'IA-2005-27', 'IA-2008-15', 'RJ-2011-00940', 'IA-2010-01', 'RJ-2012-05754', 'RJ-2011-05211', 'RJ-2013-04660', 'SP-2012-00402', 'RJ-2014-08017', '19957-003482-2017-35', 'RJ-2013-08697', 'RJ-2014-03401', 'RJ-2016-05499', 'RJ-2016-05735', 'RJ-2016-07791', 'RJ-2016-08172', 'SP-2013-00094', 'SP-2014-00014', '19957-000132-2015-55', '19957-000622-2015-51', '19957-001067-2017-47', '19957-003084-2016-38', '19957-004535-2018-16', '19957-004930-2016-37', '19957-006136-2016-28', '19957-006904-2017-24', '19957-008984-2016-71', '19957-009221-2016-48', '19957-009225-2016-26', '19957-009601-2018-44', '19957-009602-2018-99', 'RJ-2008-08046', 'RJ-2016-06086', 'RJ-2016-07808', '19957-003331-2018-68', '19957-003593-2018-22', '19957-009750-2019-94', '19957-010281-2019-56', '19957-011171-2017-40', 'IA-2007-06', '19957-001882-2020-10', '19957-008185-2021-62', '19957-007344-2019-97', '19957-012414-2022-24']

Fazemos uma análise, abrindo os pdfs da lista e observamos que os principais problemas se devem às situações em que:
1. O início do relatório é grafado como "r e l a t ó r i o";
2. A palavra "relatório" é grafada sem acento agudo no "o";
3. Em um documento em específico, vemos o início do relatório como "r e l a tó r i o";
4. O relatório, ao invés de terminar com a expressão "é o relatório", termina com a data, no estulo "LUGAR, XX de MÊS de 20XX";
5. O relatório está contido em uma xerox. Para isso, vamos ter que usar outro pacote que lê as imagens.

Vamos ajustar o código para esses casos, mudando a função de acordo com esses pontos.

In [64]:
def extrair_relatorio_2(texto):
   
    # Padrão para pegar "Relatório ... É o relatório"
    pattern_relatorio = r"(relatório|relatorio|r e l a t ó r i o|r e l a t o r i o|r e l a tó r i o)(.*?)(é o relatório|(?:Rio de Janeiro|São Paulo), (?:\d{2}|\d{1}) de (?:janeiro|fevereiro|março|abril|maio|junho|julho|agosto|setembro|outubro|novembro|dezembro) de 20\d{2}|(?:Rio de Janeiro|São Paulo),(?:\d{2}|\d{1}) de (?:janeiro|fevereiro|março|abril|maio|junho|julho|agosto|setembro|outubro|novembro|dezembro) de 20\d{2})" #Padrão
    match_relatorio = re.search(pattern_relatorio, texto, flags=re.DOTALL|re.IGNORECASE) #Procura pelo padrão

    relatorio = (match_relatorio.group(1) + match_relatorio.group(2) + match_relatorio.group(3)) if match_relatorio else np.nan #Definimos o relatório como a união das três strings.

    return relatorio #Retornamos o número do processo e o relatório.

In [65]:
df['Relatório2'] = df['Texto'].apply(extrair_relatorio_2)

df

,ID,Texto,Escaneado,Relatório,Relatório2
0,IA-1995-21,Voltar\nSESSÃO DE JULGAMENTO DO\nINQUÉRITO ADM...,False,NaN,RELATÓRIO\nRelator: Durval José Soledade Santo...
1,IA-1996-10,Voltar\nSESSÃO DE JULGAMENTO DO\nINQUÉRITO ADM...,False,NaN,RELATÓRIO\nRelator : Durval José Soledade Sant...
2,IA-1997-12,Voltar\nilde;O DE JULGAMENTO DO\nINQUÉRITO ADM...,False,RELATÓRIO\nSenhores Membros do Colegiado:\nO p...,RELATÓRIO\nSenhores Membros do Colegiado:\nO p...
3,IA-1998-01,Voltar\nSESSÃO DE JULGAMENTO DO\nINQUÉRITO ADM...,False,RELATÓRIO\nRELATOR : Diretor Durval José Soled...,RELATÓRIO\nRELATOR : Diretor Durval José Soled...
4,IA-1998-05,Voltar\nSESSÃO DE JULGAMENTO DO\nINQUÉRITO ADM...,False,RELATÓRIO COMPLEMENTAR\nRelator : Diretor Wlad...,RELATÓRIO COMPLEMENTAR\nRelator : Diretor Wlad...
...,...,...,...,...,...
1266,19957-011361-2018-48,Diário Eletrônico da CVM em\n17/07/2023\nCOMIS...,False,"Relatório, conforme o caso.\n2 O Inquérito Adm...","Relatório, conforme o caso.\n2 O Inquérito Adm..."
1267,19957-011669-2017-11,Diário Eletrônico da CVM em\n25/10/2023\nCOMIS...,False,RELATÓRIO\nI. OBJETO E ORIGEM\n1. Trata-se de ...,RELATÓRIO\nI. OBJETO E ORIGEM\n1. Trata-se de ...
1268,19957-012126-2022-70,Diário Eletrônico da CVM em\n11/08/2023\nCOMIS...,False,RELATÓRIO\nI. OBJETO\n1. Trata-se de Processo ...,RELATÓRIO\nI. OBJETO\n1. Trata-se de Processo ...
1269,19957-012414-2022-24,Diário Eletrônico da CVM em\n21/08/2023\nCOMIS...,False,NaN,relatório da administração e do\nrelatório do ...
1270,19957-015734-2022-36,Diário Eletrônico da CVM em\n01/11/2023\nCOMIS...,False,RELATÓRIO DE JULGAMENTO - GAIN\nPROCESSO ADMIN...,RELATÓRIO DE JULGAMENTO - GAIN\nPROCESSO ADMIN...

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1271 entries, 0 to 1270
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          1271 non-null   object
 1   Texto       1271 non-null   object
 2   Escaneado   1271 non-null   bool
 3   Relatório   1189 non-null   object
 4   Relatório2  1248 non-null   object
dtypes: bool(1), object(4)
memory usage: 41.1+ KB

In [67]:
df["Relatório_final"] = df["Relatório"].combine_first(df["Relatório2"])

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1271 entries, 0 to 1270
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               1271 non-null   object
 1   Texto            1271 non-null   object
 2   Escaneado        1271 non-null   bool
 3   Relatório        1189 non-null   object
 4   Relatório2       1248 non-null   object
 5   Relatório_final  1248 non-null   object
dtypes: bool(1), object(5)
memory usage: 51.0+ KB

In [69]:
ids_duplicados = df.loc[df["ID"].duplicated(), "ID"].unique()

ids_duplicados

array(['IA-1998-36', 'IA-1997-17', 'RJ-2007-04665', 'RJ-2012-06987',
       'IA-2007-06', '19957-003190-2019-64', '19957-003406-2019-91'],
      dtype=object)

In [70]:

# 1) Contar quantas vezes cada ID aparece
contagens = df["ID"].value_counts()

# 2) Filtrar apenas IDs com mais de uma ocorrência
ids_duplicados = contagens[contagens > 1].index

# 3) Criar um dataframe só com esses duplicados
df_duplicados = df[df["ID"].isin(ids_duplicados)]

print("🔎 IDs duplicados e suas contagens:")
print(contagens[contagens > 1])
print("\n📄 DataFrame apenas com linhas duplicadas:")
print(df_duplicados)

🔎 IDs duplicados e suas contagens:
ID
RJ-2007-04665           2
IA-1997-17              2
IA-2007-06              2
IA-1998-36              2
RJ-2012-06987           2
19957-003190-2019-64    2
19957-003406-2019-91    2
Name: count, dtype: int64

📄 DataFrame apenas com linhas duplicadas:
                        ID                                              Texto  \
9               IA-1998-36  Voltar\nSESSÃO DE JULGAMENTO DO\nINQUÉRITO ADM...
28              IA-1998-36  INQUÉRITO ADMINISTRATIVO Nº 36/98\nSESSÃO DE J...
190             IA-1997-17  SESSÃO DE JULGAMENTO DO PROCESSO ADMINISTRATIV...
191             IA-1997-17  SESSÃO DE JULGAMENTO\nDO PROCESSO ADMINISTRATI...
487          RJ-2007-04665  EXTRATO DA SESSÃO DE JULGAMENTO DO\nPROCESSO A...
532             IA-2007-06  EXTRATO DA SESSÃO DE JULGAMENTO DO PROCESSO AD...
626          RJ-2007-04665  EXTRATO DA SESSÃO DE JULGAMENTO DO PROCESSO AD...
652          RJ-2012-06987  EXTRATO DA SESSÃO DE JULGAMENTO DO PROCESSO AD...
687          RJ-2012-06987  EXTRATO DA SESSÃO DE JULGAMENTO DO PROCESSO AD...
1071            IA-2007-06  COMISSÃO DE VALORES MOBILIÁRIOS\nRua Sete de S...
1088  19957-003190-2019-64  Diário Eletrônico da CVM em\n06/08/2020\nCOMIS...
1089  19957-003190-2019-64  Relatório PTE (versão pública) (1028740) SEI 1...
1090  19957-003406-2019-91  Diário Eletrônico da CVM em\n11/03/2021\nCOMIS...
1091  19957-003406-2019-91  COMISSÃO DE VALORES MOBILIÁRIOS\nRua Sete de S...

      Escaneado                                          Relatório  \
9         False  RELATÓRIO\nRelator : DIRETOR WLADIMIR CASTELO ...
28        False  RELATÓRIO COMPLEMENTAR\nDIRETOR : WLADIMIR CAS...
190       False  RELATÓRIO\nSenhores Membros do Colegiado,\n1. ...
191       False  RELATÓRIO\nSenhores Membros do Colegiado,\n1. ...
487       False  Relatório\n1. Este processo foi instaurado par...
532       False  Relatório\n1. Introdução\n1.1. Este processo a...
626       False  RELATÓRIO\nI. OBJETO\n1. Trata-se de processo ...
652       False  Relatório\nI. Apresentação de Termo de Comprom...
687       False  RELATÓRIO\nI. DO JULGAMENTO DA ADMINISTRADORA ...
1071       True                                                NaN
1088      False  Relatório\nI. Objeto\n1. Trata-se de processo ...
1089      False  Relatório PTE (versão pública) (1028740) SEI 1...
1090      False  RELATÓRIO\nI. INTRODUÇÃO\n1. Este Processo Adm...
1091      False  RELATÓRIO\nI. INTRODUÇÃO\n1. Este Processo Adm...

                                             Relatório2  \
9     RELATÓRIO\nRelator : DIRETOR WLADIMIR CASTELO ...
28    RELATÓRIO COMPLEMENTAR\nDIRETOR : WLADIMIR CAS...
190   RELATÓRIO\nSenhores Membros do Colegiado,\n1. ...
191   RELATÓRIO\nSenhores Membros do Colegiado,\n1. ...
487   Relatório\n1. Este processo foi instaurado par...
532   Relatório\n1. Introdução\n1.1. Este processo a...
626   RELATÓRIO\nI. OBJETO\n1. Trata-se de processo ...
652   Relatório\nI. Apresentação de Termo de Comprom...
687   RELATÓRIO\nI. DO JULGAMENTO DA ADMINISTRADORA ...
1071                                                NaN
1088  Relatório\nI. Objeto\n1. Trata-se de processo ...
1089  Relatório PTE (versão pública) (1028740) SEI 1...
1090  RELATÓRIO\nI. INTRODUÇÃO\n1. Este Processo Adm...
1091  relatório que antecede este voto.\n2 Com o per...

                                        Relatório_final
9     RELATÓRIO\nRelator : DIRETOR WLADIMIR CASTELO ...
28    RELATÓRIO COMPLEMENTAR\nDIRETOR : WLADIMIR CAS...
190   RELATÓRIO\nSenhores Membros do Colegiado,\n1. ...
191   RELATÓRIO\nSenhores Membros do Colegiado,\n1. ...
487   Relatório\n1. Este processo foi instaurado par...
532   Relatório\n1. Introdução\n1.1. Este processo a...
626   RELATÓRIO\nI. OBJETO\n1. Trata-se de processo ...
652   Relatório\nI. Apresentação de Termo de Comprom...
687   RELATÓRIO\nI. DO JULGAMENTO DA ADMINISTRADORA ...
1071                                                NaN
1088  Relatório\nI. Objeto\n1. Trata-se de processo ...
1089  Relatório PTE (versão pública) (1028740) SEI 1...
1090  RELATÓRIO\nI. INTRODUÇÃO\n1. Este Processo Adm...
1091  RELATÓRIO\nI. INTRODUÇÃO\n1. Este Processo Adm...

In [71]:
df = df.drop(index=[28, 191, 487, 1071, 687, 1089, 1090])

In [72]:
df[df["Relatório_final"].isna()]

,ID,Texto,Escaneado,Relatório,Relatório2,Relatório_final
444,IA-2006-01,EXTRATO DA SESSÃO DE JULGAMENTO DO PROCESSO\nA...,False,NaN,NaN,NaN
491,RJ-2007-14153,EXTRATO DA SESSÃO DE JULGAMENTO DO PROCESSO AD...,False,NaN,NaN,NaN
763,SP-2012-00402,EXTRATO DA SESSÃO DE JULGAMENTO DO PROCESSO AD...,False,NaN,NaN,NaN
879,19957-000132-2015-55,(cid:0)(cid:0)(cid:1)(cid:0)(cid:2)(cid:1)(cid...,False,NaN,NaN,NaN
881,19957-000622-2015-51,(cid:0)(cid:0)(cid:1)(cid:0)(cid:2)(cid:1)(cid...,False,NaN,NaN,NaN
884,19957-001067-2017-47,SEI/CVM - 0594322 - Extrato de Sessão de Julga...,True,NaN,NaN,NaN
891,19957-003084-2016-38,(cid:0)(cid:1)(cid:2)(cid:0)(cid:3)(cid:2)(cid...,False,NaN,NaN,NaN
897,19957-004535-2018-16,COMISSÃO DE VALORES MOBILIÁRIOS\nEXTRATO DE SE...,False,NaN,NaN,NaN
900,19957-004930-2016-37,(cid:0)(cid:1)(cid:2)(cid:0)(cid:3)(cid:2)(cid...,False,NaN,NaN,NaN
902,19957-006136-2016-28,(cid:0)(cid:0)(cid:1)(cid:0)(cid:2)(cid:1)(cid...,False,NaN,NaN,NaN
905,19957-006904-2017-24,(cid:0)(cid:1)(cid:2)(cid:0)(cid:3)(cid:2)(cid...,False,NaN,NaN,NaN
910,19957-008984-2016-71,(cid:0)(cid:1)(cid:2)(cid:0)(cid:3)(cid:2)(cid...,False,NaN,NaN,NaN
911,19957-009221-2016-48,COMISSÃO DE VALORES MOBILIÁRIOS\nEXTRATO DE SE...,False,NaN,NaN,NaN
912,19957-009225-2016-26,COMISSÃO DE VALORES MOBILIÁRIOS\nEXTRATO DE SE...,False,NaN,NaN,NaN
915,19957-009601-2018-44,(cid:0)(cid:0)(cid:1)(cid:0)(cid:2)(cid:1)(cid...,False,NaN,NaN,NaN
916,19957-009602-2018-99,(cid:0)(cid:0)(cid:1)(cid:0)(cid:2)(cid:1)(cid...,False,NaN,NaN,NaN
960,RJ-2016-07808,(cid:0)(cid:1)(cid:2)(cid:3)(cid:4)(cid:2)(cid...,False,NaN,NaN,NaN
1013,19957-003593-2018-22,COMISSÃO DE VALORES MOBILIÁRIOS\nEXTRATO DE SE...,False,NaN,NaN,NaN
1052,19957-009750-2019-94,Diário Eletrônico da CVM em\n11/12/2019\nCOMIS...,False,NaN,NaN,NaN
1057,19957-010281-2019-56,Diário Eletrônico da CVM em\n20/12/2019\nCOMIS...,False,NaN,NaN,NaN
1062,19957-011171-2017-40,Diário Eletrônico da CVM em 31/07/2019\nDOU de...,False,NaN,NaN,NaN
1083,19957-001882-2020-10,Diário Eletrônico da CVM em\n26/03/2020\nCOMIS...,False,NaN,NaN,NaN

In [75]:
df.loc[444, "Relatório_final"] = re.search(r"(R E L A T Ó R I O.*?aos demais acusados)", df.loc[444, "Texto"], flags=re.DOTALL).group(1) if re.search(r"(R E L A T Ó R I O.*?aos demais acusados)", df.loc[444, "Texto"], flags=re.DOTALL) else np.nan
df.loc[491, "Relatório_final"] = re.search(r"(Relatório.*?suspensão do processo em relação a eles)", df.loc[491, "Texto"], flags=re.DOTALL).group(1) if re.search(r"(Relatório.*?suspensão do processo em relação a eles)", df.loc[491, "Texto"], flags=re.DOTALL) else np.nan
df.loc[763, "Relatório_final"] = re.search(r"(Relatório.*?julho de 2015)", df.loc[763, "Texto"], flags=re.DOTALL).group(1) if re.search(r"(Relatório.*?julho de 2015)", df.loc[763, "Texto"], flags=re.DOTALL) else np.nan
df.loc[897, "Relatório_final"] = re.search(r"(Relatório.*?cabíveis)", df.loc[897, "Texto"], flags=re.DOTALL).group(1) if re.search(r"(Relatório.*?cabíveis)", df.loc[897, "Texto"], flags=re.DOTALL) else np.nan
df.loc[911, "Relatório_final"] = re.search(r"(Relatório.*?deste mesmo artigo)", df.loc[911, "Texto"], flags=re.DOTALL).group(1) if re.search(r"(Relatório.*?deste mesmo artigo)", df.loc[911, "Texto"], flags=re.DOTALL) else np.nan
df.loc[912, "Relatório_final"] = re.search(r"(Relatório.*?deste mesmo artigo)", df.loc[912, "Texto"], flags=re.DOTALL).group(1) if re.search(r"(Relatório.*?deste mesmo artigo)", df.loc[912, "Texto"], flags=re.DOTALL) else np.nan


print(df.loc[[444, 491, 763, 897, 911, 912], ["Texto", "Relatório_final"]])

                                                 Texto  \
444  EXTRATO DA SESSÃO DE JULGAMENTO DO PROCESSO\nA...
491  EXTRATO DA SESSÃO DE JULGAMENTO DO PROCESSO AD...
763  EXTRATO DA SESSÃO DE JULGAMENTO DO PROCESSO AD...
897  COMISSÃO DE VALORES MOBILIÁRIOS\nEXTRATO DE SE...
911  COMISSÃO DE VALORES MOBILIÁRIOS\nEXTRATO DE SE...
912  COMISSÃO DE VALORES MOBILIÁRIOS\nEXTRATO DE SE...

                                       Relatório_final
444  R E L A T Ó R I O\n1. Introdução\n1.1 Trata-se...
491  Relatório\n1. A Superintendência de Investidor...
763  Relatório\nI. Introdução\n1. Trata-se de proce...
897  Relatório nº 67/2018-CVM/SEP/GEA-4\nPara: GEA-...
911  Relatório nº 6/2018-CVM/SNC\nAssunto: Processo...
912  Relatório nº 1/2018-CVM/SNC\nAssunto: Processo...

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1264 entries, 0 to 1270
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               1264 non-null   object
 1   Texto            1264 non-null   object
 2   Escaneado        1264 non-null   bool
 3   Relatório        1183 non-null   object
 4   Relatório2       1242 non-null   object
 5   Relatório_final  1248 non-null   object
dtypes: bool(1), object(5)
memory usage: 92.8+ KB

In [77]:
df = df.drop(columns=["Relatório", "Relatório2"])

In [78]:
df = df.rename(columns={"Relatório_final": "Relatório"})

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1264 entries, 0 to 1270
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         1264 non-null   object
 1   Texto      1264 non-null   object
 2   Escaneado  1264 non-null   bool
 3   Relatório  1248 non-null   object
dtypes: bool(1), object(3)
memory usage: 73.0+ KB

In [79]:
df.to_csv("D:/Backup Tomas/T0mas/Faculdade/IC/Geral/Github CVM/corporate-fraud-in-brazil/data/interim/relatorios_dos_processos/relatorios_esjs.csv", index=False)