# Extração dos Relatórios - PCTCs

O objetivo deste código é extrair os relatórios dos textos referentes aos Pareceres do Comitê de Termo de Compromisso.

Para isso, usaremos os dados que contém os textos dos processos, e faremos uso de expressões regulares para delimitar o início e o fim do relatório.

In [74]:
import os
import pandas as pd
import re
import random
import numpy as np
import time
import ast

In [75]:
def extrair_relatorio(texto):

    # Padrão para pegar "Relatório ... É o relatório"
    pattern_relatorio = r"(relatório|fatos|dos fatos|da origem)(.*?)(é o relatório|parecer técnico finalizado em|parecer finalizado em|da conclusão|(?:Rio de Janeiro|São Paulo), (?:\d{2}|\d{1}) de (?:janeiro|fevereiro|março|abril|maio|junho|julho|agosto|setembro|outubro|novembro|dezembro) de 20\d{2})" #Padrão
    match_relatorio = re.search(pattern_relatorio, texto, flags=re.DOTALL|re.IGNORECASE) #Procura pelo padrão

    relatorio = (match_relatorio.group(1) + match_relatorio.group(2) + match_relatorio.group(3)) if match_relatorio else np.nan #Definimos o relatório como a união das três strings.

    return relatorio #Retornamos o número do processo e o relatório.

In [76]:
df['Relatório'] = df['Texto'].apply(extrair_relatorio)

df

,ID,Texto,Escaneado,Relatório,len_rel
0,RJ-2009-01,PROCESSO DE TERMO DE COMPROMISSO CVM Nº RJ2012...,False,Relatório\n1. Trata-se de nova proposta de Ter...,5798.0
1,RJ-2012-12067,PROCESSO DE TERMO DE COMPROMISSO CVM Nº RJ2012...,False,Relatório\n1. Trata-se de nova proposta de Ter...,5798.0
2,IA-2012-01,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,False,RELATÓRIO\n1. Trata-se de proposta de Termo de...,20971.0
3,RJ-2013-08159,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,False,RELATÓRIO\n1. Trata-se de proposta de Termo de...,20971.0
4,IA-2001-02,INQUÉRITO ADMINISTRATIVO CVM Nº 02/01\nASSUNTO...,False,RELATÓRIO\nTrata-se de apreciação de propostas...,9391.0
...,...,...,...,...,...
694,RJ-2013-08604,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,False,RELATÓRIO\nFATOS\n1. Trata-se de proposta de T...,11734.0
695,SP-2013-00157,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,False,RELATÓRIO\n1. Trata-se de proposta de Termo de...,9385.0
696,SP-2013-00260,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,False,RELATÓRIO\n1. Trata-se de proposta de Termo de...,5759.0
697,SP-2013-00295,PARRECER DOO COMITÊÊ DE TERMMO DE COOMPROMIISS...,False,NaN,NaN
698,SP-2013-00097,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,False,RELATÓRIO\n1. Trata-se de propostas de Termo d...,20270.0

In [77]:
df = pd.read_csv("D:/Backup Tomas/T0mas/Faculdade/IC/Geral/Github CVM/corporate-fraud-in-brazil/data/interim/textos_dos_processos/textos_pctcs.csv")

In [78]:
print(df)

                                       ID  \
0                    01_2009-RJ2012_12067
1                   01_2012 - RJ2013_8159
2    02_01 - CIA. PAULISTA DE FERRO E GÁS
3    02_01 - CIA. PAULISTA DE FERRO E GÁS
4           04_01 E - SP 2002_0235 - BM&F
..                                    ...
740               SP2013_12 - RJ2013_8604
741                            SP2013_157
742                            SP2013_260
743                            SP2013_295
744                             SP2013_97

                                                 Texto  \
0    PROCESSO DE TERMO DE COMPROMISSO CVM Nº RJ2012...
1    PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...
2    INQUÉRITO ADMINISTRATIVO CVM Nº 02/01\nASSUNTO...
3    INQUÉRITO ADMINISTRATIVO CVM Nº 02/01\nASSUNTO...
4    Processos Administrativos Sancionadores CVM 04...
..                                                 ...
740  PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...
741  PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...
742  PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...
743  PARRECER DOO COMITÊÊ DE TERMMO DE COOMPROMIISS...
744  PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...

       identificador_lista_transformada  Escaneado
0       ['RJ-2009-01', 'RJ-2012-12067']      False
1       ['IA-2012-01', 'RJ-2013-08159']      False
2                        ['IA-2001-02']      False
3                        ['IA-2001-02']      False
4                        ['IA-2001-04']      False
..                                  ...        ...
740  ['SP-2013-00012', 'RJ-2013-08604']      False
741                   ['SP-2013-00157']      False
742                   ['SP-2013-00260']      False
743                   ['SP-2013-00295']      False
744                   ['SP-2013-00097']      False

[745 rows x 4 columns]

In [79]:
def extrair_relatorio(texto):

    # Padrão para pegar "Relatório ... É o relatório"
    pattern_relatorio = r"(relatório|fatos|dos fatos|da origem)(.*?)(é o relatório|parecer técnico finalizado em|parecer finalizado em|da conclusão|(?:Rio de Janeiro|São Paulo), (?:\d{2}|\d{1}) de (?:janeiro|fevereiro|março|abril|maio|junho|julho|agosto|setembro|outubro|novembro|dezembro) de 20\d{2})" #Padrão
    match_relatorio = re.search(pattern_relatorio, texto, flags=re.DOTALL|re.IGNORECASE) #Procura pelo padrão

    relatorio = (match_relatorio.group(1) + match_relatorio.group(2) + match_relatorio.group(3)) if match_relatorio else np.nan #Definimos o relatório como a união das três strings.

    return relatorio #Retornamos o número do processo e o relatório.

In [80]:
df['Relatório'] = df['Texto'].apply(extrair_relatorio)

df

,ID,Texto,identificador_lista_transformada,Escaneado,Relatório
0,01_2009-RJ2012_12067,PROCESSO DE TERMO DE COMPROMISSO CVM Nº RJ2012...,"['RJ-2009-01', 'RJ-2012-12067']",False,Relatório\n1. Trata-se de nova proposta de Ter...
1,01_2012 - RJ2013_8159,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,"['IA-2012-01', 'RJ-2013-08159']",False,RELATÓRIO\n1. Trata-se de proposta de Termo de...
2,02_01 - CIA. PAULISTA DE FERRO E GÁS,INQUÉRITO ADMINISTRATIVO CVM Nº 02/01\nASSUNTO...,['IA-2001-02'],False,RELATÓRIO\nTrata-se de apreciação de propostas...
3,02_01 - CIA. PAULISTA DE FERRO E GÁS,INQUÉRITO ADMINISTRATIVO CVM Nº 02/01\nASSUNTO...,['IA-2001-02'],False,RELATÓRIO\nTrata-se de apreciação de propostas...
4,04_01 E - SP 2002_0235 - BM&F,Processos Administrativos Sancionadores CVM 04...,['IA-2001-04'],False,Relatório\n1. No Processo Administrativo Sanci...
...,...,...,...,...,...
740,SP2013_12 - RJ2013_8604,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,"['SP-2013-00012', 'RJ-2013-08604']",False,RELATÓRIO\nFATOS\n1. Trata-se de proposta de T...
741,SP2013_157,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,['SP-2013-00157'],False,RELATÓRIO\n1. Trata-se de proposta de Termo de...
742,SP2013_260,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,['SP-2013-00260'],False,RELATÓRIO\n1. Trata-se de proposta de Termo de...
743,SP2013_295,PARRECER DOO COMITÊÊ DE TERMMO DE COOMPROMIISS...,['SP-2013-00295'],False,NaN
744,SP2013_97,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,['SP-2013-00097'],False,RELATÓRIO\n1. Trata-se de propostas de Termo d...

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 745 entries, 0 to 744
Data columns (total 5 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ID                                745 non-null    object
 1   Texto                             745 non-null    object
 2   identificador_lista_transformada  745 non-null    object
 3   Escaneado                         745 non-null    bool
 4   Relatório                         697 non-null    object
dtypes: bool(1), object(4)
memory usage: 24.1+ KB

In [82]:
def extrair_relatorio_2(texto):

    # Padrão para pegar "Relatório ... É o relatório"
    pattern_relatorio = r"(FATOS)(.*?)(CONCLUSÃO|DA CONCLUSÃO)" #Padrão
    match_relatorio = re.search(pattern_relatorio, texto, flags=re.DOTALL) #Procura pelo padrão

    relatorio = (match_relatorio.group(1) + match_relatorio.group(2) + match_relatorio.group(3)) if match_relatorio else np.nan #Definimos o relatório como a união das três strings.

    return relatorio #Retornamos o número do processo e o relatório.

In [83]:
df['Relatório2'] = df['Texto'].apply(extrair_relatorio_2)

df

,ID,Texto,identificador_lista_transformada,Escaneado,Relatório,Relatório2
0,01_2009-RJ2012_12067,PROCESSO DE TERMO DE COMPROMISSO CVM Nº RJ2012...,"['RJ-2009-01', 'RJ-2012-12067']",False,Relatório\n1. Trata-se de nova proposta de Ter...,NaN
1,01_2012 - RJ2013_8159,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,"['IA-2012-01', 'RJ-2013-08159']",False,RELATÓRIO\n1. Trata-se de proposta de Termo de...,FATOS\n2. O presente processo surgiu a partir ...
2,02_01 - CIA. PAULISTA DE FERRO E GÁS,INQUÉRITO ADMINISTRATIVO CVM Nº 02/01\nASSUNTO...,['IA-2001-02'],False,RELATÓRIO\nTrata-se de apreciação de propostas...,NaN
3,02_01 - CIA. PAULISTA DE FERRO E GÁS,INQUÉRITO ADMINISTRATIVO CVM Nº 02/01\nASSUNTO...,['IA-2001-02'],False,RELATÓRIO\nTrata-se de apreciação de propostas...,NaN
4,04_01 E - SP 2002_0235 - BM&F,Processos Administrativos Sancionadores CVM 04...,['IA-2001-04'],False,Relatório\n1. No Processo Administrativo Sanci...,NaN
...,...,...,...,...,...,...
740,SP2013_12 - RJ2013_8604,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,"['SP-2013-00012', 'RJ-2013-08604']",False,RELATÓRIO\nFATOS\n1. Trata-se de proposta de T...,FATOS\n1. Trata-se de proposta de Termo de Com...
741,SP2013_157,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,['SP-2013-00157'],False,RELATÓRIO\n1. Trata-se de proposta de Termo de...,FATOS\n2. Em decorrência de relatórios de audi...
742,SP2013_260,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,['SP-2013-00260'],False,RELATÓRIO\n1. Trata-se de proposta de Termo de...,FATOS\n2. No curso de investigação envolvendo ...
743,SP2013_295,PARRECER DOO COMITÊÊ DE TERMMO DE COOMPROMIISS...,['SP-2013-00295'],False,NaN,NaN
744,SP2013_97,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,['SP-2013-00097'],False,RELATÓRIO\n1. Trata-se de propostas de Termo d...,FATOS\n2. O presente processo surgiu a partir ...

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 745 entries, 0 to 744
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ID                                745 non-null    object
 1   Texto                             745 non-null    object
 2   identificador_lista_transformada  745 non-null    object
 3   Escaneado                         745 non-null    bool
 4   Relatório                         697 non-null    object
 5   Relatório2                        456 non-null    object
dtypes: bool(1), object(5)
memory usage: 30.0+ KB

In [85]:
df["Relatório_final"] = df["Relatório"].combine_first(df["Relatório2"])

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 745 entries, 0 to 744
Data columns (total 7 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ID                                745 non-null    object
 1   Texto                             745 non-null    object
 2   identificador_lista_transformada  745 non-null    object
 3   Escaneado                         745 non-null    bool
 4   Relatório                         697 non-null    object
 5   Relatório2                        456 non-null    object
 6   Relatório_final                   714 non-null    object
dtypes: bool(1), object(6)
memory usage: 35.8+ KB

In [87]:
df = df.drop_duplicates()

In [88]:
df["len_rel"] = df["Relatório_final"].str.len()

# 1) Contar quantas vezes cada ID aparece
contagens = df["ID"].value_counts()

# 2) Filtrar apenas IDs com mais de uma ocorrência
ids_duplicados = contagens[contagens > 1].index

# 3) Criar um dataframe só com esses duplicados
df_duplicados = df[df["ID"].isin(ids_duplicados)]

print("🔎 IDs duplicados e suas contagens:")
print(contagens[contagens > 1])
print("\n📄 DataFrame apenas com linhas duplicadas:")
df_duplicados

🔎 IDs duplicados e suas contagens:
ID
19957.008782_2016-20 e 19957.004666_2017-12    2
19957.005332_2018-47​                          2
11_2012 - RJ2014_27                            2
19957.002923_2017-81                           2
19957.004923_2016-35                           2
16_2008                                        2
19957.009486_2017-27                           2
06_04                                          2
22_06                                          2
RJ2007_1854                                    2
RJ2008_3931                                    2
Name: count, dtype: int64

📄 DataFrame apenas com linhas duplicadas:

C:\Users\Tomás\AppData\Local\Temp\ipykernel_23252\2184308028.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["len_rel"] = df["Relatório_final"].str.len()

,ID,Texto,identificador_lista_transformada,Escaneado,Relatório,Relatório2,Relatório_final,len_rel
8,06_04,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nREF...,['IA-2004-06'],False,RELATÓRIO\n1. Trata-se de nova proposta de Ter...,NaN,RELATÓRIO\n1. Trata-se de nova proposta de Ter...,8371.0
9,06_04,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nREF...,['IA-2004-06'],False,RELATÓRIO\n1. Trata-se de Inquérito Administra...,NaN,RELATÓRIO\n1. Trata-se de Inquérito Administra...,42737.0
31,11_2012 - RJ2014_27,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,"['IA-2012-11', 'RJ-2014-00027']",False,RELATÓRIO\n1. Trata-se de propostas de celebra...,FATOS\n2. O presente processo resultou de recl...,RELATÓRIO\n1. Trata-se de propostas de celebra...,17112.0
32,11_2012 - RJ2014_27,:: SEI / CVM - 0042291 - Memorando :: https://...,"['IA-2012-11', 'RJ-2014-00027']",False,NaN,NaN,NaN,NaN
48,16_2008,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,['IA-2008-16'],False,RELATÓRIO\n1. Trata-se de nova proposta de Ter...,FATOS\n4. À época em que ocorreram as operaçõe...,RELATÓRIO\n1. Trata-se de nova proposta de Ter...,31658.0
49,16_2008,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,['IA-2008-16'],False,RELATÓRIO\n1. Trata-se de novas propostas de T...,NaN,RELATÓRIO\n1. Trata-se de novas propostas de T...,52460.0
127,19957.002923_2017-81,COMISSÃO DE VALORES MOBILIÁRIOS\nPARECER DO CO...,['19957-002923-2017-81'],False,Relatório de Inquérito ) até a\ndata do efetiv...,FATOS E ANÁLISE DA ÁREA TÉCNICA\n10. Em 23.12....,Relatório de Inquérito ) até a\ndata do efetiv...,33570.0
128,19957.002923_2017-81,COMISSÃO DE VALORES MOBILIÁRIOS\nPARECER DO CO...,['19957-002923-2017-81'],False,DA ORIGEM[4]\n2. O Inquérito Administrativo te...,"FATOS\n8. Em 23.12.2013, foi publicado o edita...",DA ORIGEM[4]\n2. O Inquérito Administrativo te...,82389.0
193,19957.004923_2016-35,COMISSÃO DE VALORES MOBILIÁRIOS\nRua Sete de S...,['19957-004923-2016-35'],False,Relatório\n1. Trata-se de proposta de termo de...,NaN,Relatório\n1. Trata-se de proposta de termo de...,29534.0
194,19957.004923_2016-35,COMISSÃO DE VALORES MOBILIÁRIOS\nRua Sete de S...,['19957-004923-2016-35'],False,Relatório\n1. Trata-se de proposta de termo de...,NaN,Relatório\n1. Trata-se de proposta de termo de...,27811.0
207,19957.005332_2018-47​,SEI/CVM - 0921319 - Parecer do CTC https://sei...,['19957-005332-2018-47'],False,RELATÓRIO\nPARECER DO COMITÊ DE TERMO DE COMPR...,FATOS\n2. O processo foi instaurado para análi...,RELATÓRIO\nPARECER DO COMITÊ DE TERMO DE COMPR...,16956.0
208,19957.005332_2018-47​,COMISSÃO DE VALORES MOBILIÁRIOS\nPARECER DO CO...,['19957-005332-2018-47'],False,RELATÓRIO\n1. Trata-se de proposta conjunta de...,FATOS\n2. O processo foi instaurado para análi...,RELATÓRIO\n1. Trata-se de proposta conjunta de...,26864.0
318,19957.008782_2016-20 e 19957.004666_2017-12,COMISSÃO DE VALORES MOBILIÁRIOS\nPARECER DO CO...,"['19957-008782-2016-20', '19957-004666-2017-12']",False,fatos imputados às pessoas jurídicas objeto do...,FATOS\n8. Os processos tiveram origem[2] a par...,fatos imputados às pessoas jurídicas objeto do...,9535.0
319,19957.008782_2016-20 e 19957.004666_2017-12,COMISSÃO DE VALORES MOBILIÁRIOS\nPARECER DO CO...,"['19957-008782-2016-20', '19957-004666-2017-12']",False,RELATÓRIO\nPROCESSO ADMINISTRATIVO SANCIONADOR...,FATOS\n3. Os processos tiveram origem[2] a par...,RELATÓRIO\nPROCESSO ADMINISTRATIVO SANCIONADOR...,8966.0
337,19957.009486_2017-27,COMISSÃO DE VALORES MOBILIÁRIOS\nPARECER DO CO...,['19957-009486-2017-27'],False,RELATÓRIO\n1. Trata-se de proposta de Termo de...,"FATOS\n8. Em 19.02.2014, a OSA protocolou na C...",RELATÓRIO\n1. Trata-se de proposta de Termo de...,20482.0
338,19957.009486_2017-27,COMISSÃO DE VALORES MOBILIÁRIOS\nPARECER DO CO...,['19957-009486-2017-27'],False,RELATÓRIO\n1. Trata-se de proposta de Termo de...,"FATOS\n4. Em 19.02.2014, a Oi protocolou na CV...",RELATÓRIO\n1. Trata-se de proposta de Termo de...,17417.0
433,22_06,PROCESSO ADMINISTRATIVO SANCIONADOR CVM N° 22/...,['IA-2006-22'],False,NaN,NaN,NaN,NaN
434,22_06,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nREF...,['IA-2006-22'],False,RELATÓRIO:\n1. Trata-se de inquérito administr...,NaN,RELATÓRIO:\n1. Trata-se de inquérito administr...,36446.0
535,RJ2007_1854,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nREF...,['RJ-2007-01854'],False,NaN,NaN,NaN,NaN
536,RJ2007_1854,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nREF...,['RJ-2007-01854'],False,RELATÓRIO\n1. Trata-se da apreciação de nova p...,NaN,RELATÓRIO\n1. Trata-se da apreciação de nova p...,19266.0
566,RJ2008_3931,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nREF...,['RJ-2008-03931'],False,RELATÓRIO\n1. Trata-se de proposta de Termo de...,NaN,RELATÓRIO\n1. Trata-se de proposta de Termo de...,11493.0
567,RJ2008_3931,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nREF...,['RJ-2008-03931'],False,RELATÓRIO\n1. Trata-se de proposta de Termo de...,NaN,RELATÓRIO\n1. Trata-se de proposta de Termo de...,14732.0

In [89]:
df = df.drop(index=[8, 32, 49, 127, 194, 208, 319, 338, 433, 535, 566])

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 652 entries, 0 to 744
Data columns (total 8 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ID                                652 non-null    object
 1   Texto                             652 non-null    object
 2   identificador_lista_transformada  652 non-null    object
 3   Escaneado                         652 non-null    bool
 4   Relatório                         617 non-null    object
 5   Relatório2                        408 non-null    object
 6   Relatório_final                   626 non-null    object
 7   len_rel                           626 non-null    float64
dtypes: bool(1), float64(1), object(6)
memory usage: 41.4+ KB

In [91]:
df[df["Relatório_final"].isna()]

,ID,Texto,identificador_lista_transformada,Escaneado,Relatório,Relatório2,Relatório_final,len_rel
124,19957.002813_2017-10,COMISSÃO DE VALORES MOBILIÁRIOS\nPARECER DO CO...,['19957-002813-2017-10'],False,NaN,NaN,NaN,NaN
242,19957.006298_2016-66,COMISSÃO DE VALORES MOBILIÁRIOS\nDESPACHO - SG...,['19957-006298-2016-66'],False,NaN,NaN,NaN,NaN
281,19957.007369_2021-13,"S ONRS\nU.. ...\n\nã\nDS\nS\n\nZ\n\n."".\n\ncvc...",['19957-007369-2021-13'],True,NaN,NaN,NaN,NaN
285,19957.007486_2018-73,COMISSÃO DE VALORES MOBILIÁRIOS\nDESPACHO - SG...,['19957-007486-2018-73'],False,NaN,NaN,NaN,NaN
345,19957.009719_2017-91,COMISSÃO DE VALORES MOBILIÁRIOS\nDESPACHO - SG...,['19957-009719-2017-91'],False,NaN,NaN,NaN,NaN
349,19957.009798_2019-01,COMISSÃO DE VALORES MOBILIÁRIOS\nRua Sete de S...,['19957-009798-2019-01'],False,NaN,NaN,NaN,NaN
443,RJ2001_12098 - BB DTVM,PROCESSO CVM RJ 2001/12098\nREGISTRO COLEGIADO...,['RJ-2001-12098'],False,NaN,NaN,NaN,NaN
450,RJ2002_2555 - BANCO SANTANDER,INQUÉRITO ADMINISTRATIVO CVM n° 2002/02555\nAS...,['RJ-2002-02555'],False,NaN,NaN,NaN,NaN
521,RJ2007_10681,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nREF...,['RJ-2007-10681'],False,NaN,NaN,NaN,NaN
528,RJ2007_12231,Para: SGE/CGP Memo/PFE-CVM/nº 965/08\nDe: PFE ...,['RJ-2007-12231'],False,NaN,NaN,NaN,NaN
529,RJ2007_12581,Processo Administrativo RJ 2007/12581\nReg. Co...,['RJ-2007-12581'],False,NaN,NaN,NaN,NaN
565,RJ2008_3539,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,['RJ-2008-03539'],False,NaN,NaN,NaN,NaN
609,RJ2010_4953,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nREF...,['RJ-2010-04953'],False,NaN,NaN,NaN,NaN
660,RJ2013_10745,PARRECER DOO COMITÊÊ DE TERMMO DE COOMPROMIISS...,['RJ-2013-10745'],False,NaN,NaN,NaN,NaN
663,RJ2013_11716,PARRECER DOO COMITÊÊ DE TERMMO DE COOMPROMIISS...,['RJ-2013-11716'],False,NaN,NaN,NaN,NaN
664,RJ2013_1205,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,['RJ-2013-01205'],False,NaN,NaN,NaN,NaN
665,RJ2013_12570,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,['RJ-2013-12570'],False,NaN,NaN,NaN,NaN
666,RJ2013_144,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,['RJ-2013-00144'],False,NaN,NaN,NaN,NaN
691,RJ2013_9737,PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...,['RJ-2013-09737'],False,NaN,NaN,NaN,NaN
692,RJ2014_10859,PARRECER DOO COMITÊÊ DE TERMMO DE COOMPROMIISS...,['RJ-2014-10859'],False,NaN,NaN,NaN,NaN
695,RJ2014_13902,COMISSÃO DE VALORESS MOBILIÁÁRIOS\nPARRECER DO...,['RJ-2014-13902'],False,NaN,NaN,NaN,NaN
704,RJ2014_7213,Proocesso Admministrativoo Sancionaddor CVM nn...,['RJ-2014-07213'],False,NaN,NaN,NaN,NaN
705,RJ2014_7604,PARRECER DOO COMITÊÊ DE TERMMO DE COOMPROMIISS...,['RJ-2014-07604'],False,NaN,NaN,NaN,NaN
708,RJ2014_9501,PARRECER DOO COMITÊÊ DE TERMMO DE COOMPROMIISS...,['RJ-2014-09501'],False,NaN,NaN,NaN,NaN
713,RJ2015_3247,COMISSÃO DE VALORESS MOBILIÁÁRIOS\nPARRECER DO...,['RJ-2015-03247'],False,NaN,NaN,NaN,NaN
743,SP2013_295,PARRECER DOO COMITÊÊ DE TERMMO DE COOMPROMIISS...,['SP-2013-00295'],False,NaN,NaN,NaN,NaN

In [92]:
df.loc[124, "Relatório_final"] = re.search(r"(PARECER DO COMITÊ DE TERMO DE COMPROMISSO.*?Marcelo Epperlein)", df.loc[124, "Texto"], flags=re.DOTALL).group(1) if re.search(r"(PARECER DO COMITÊ DE TERMO DE COMPROMISSO.*?Marcelo Epperlein)", df.loc[124, "Texto"], flags=re.DOTALL) else np.nan
df.loc[521, "Relatório_final"] = re.search(r"(RELATÓRIO.*?abril de 2008)", df.loc[521, "Texto"], flags=re.DOTALL).group(1) if re.search(r"(RELATÓRIO.*?abril de 2008)", df.loc[521, "Texto"], flags=re.DOTALL) else np.nan
df.loc[528, "Relatório_final"] = df.loc[528, "Texto"]
df.loc[565, "Relatório_final"] = re.search(r"(RELATÓRIO.*?novembro de 2010)", df.loc[565, "Texto"], flags=re.DOTALL).group(1) if re.search(r"(RELATÓRIO.*?novembro de 2010)", df.loc[565, "Texto"], flags=re.DOTALL) else np.nan
df.loc[609, "Relatório_final"] = re.search(r"(RELATÓRIO.*?dezembro de 2010)", df.loc[609, "Texto"], flags=re.DOTALL).group(1) if re.search(r"(RELATÓRIO.*?dezembro de 2010)", df.loc[609, "Texto"], flags=re.DOTALL) else np.nan
df.loc[664, "Relatório_final"] = re.search(r"(RELATÓRIO.*?julho de 2014)", df.loc[664, "Texto"], flags=re.DOTALL).group(1) if re.search(r"(RELATÓRIO.*?julho de 2014)", df.loc[664, "Texto"], flags=re.DOTALL) else np.nan
df.loc[665, "Relatório_final"] = re.search(r"(RELATÓRIO.*?julho de 2014)", df.loc[665, "Texto"], flags=re.DOTALL).group(1) if re.search(r"(RELATÓRIO.*?julho de 2014)", df.loc[665, "Texto"], flags=re.DOTALL) else np.nan
df.loc[666, "Relatório_final"] = re.search(r"(RELATÓRIO.*?setembro de 2013)", df.loc[666, "Texto"], flags=re.DOTALL).group(1) if re.search(r"(RELATÓRIO.*?setembro de 2013)", df.loc[666, "Texto"], flags=re.DOTALL) else np.nan
df.loc[691, "Relatório_final"] = re.search(r"(RELATÓRIO.*?julho de 2014)", df.loc[691, "Texto"], flags=re.DOTALL).group(1) if re.search(r"(RELATÓRIO.*?julho de 2014)", df.loc[691, "Texto"], flags=re.DOTALL) else np.nan

# Exibir linhas já tratadas anteriormente
print(df.loc[[124, 521, 528, 565, 609, 664, 665, 666, 691], ["Texto", "Relatório_final"]])

                                                 Texto  \
124  COMISSÃO DE VALORES MOBILIÁRIOS\nPARECER DO CO...
521  PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nREF...
528  Para: SGE/CGP Memo/PFE-CVM/nº 965/08\nDe: PFE ...
565  PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...
609  PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nREF...
664  PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...
665  PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...
666  PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...
691  PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...

                                       Relatório_final
124  PARECER DO COMITÊ DE TERMO DE COMPROMISSO\nPRO...
521  RELATÓRIO\n1. Trata-se de Termo de Acusação (f...
528  Para: SGE/CGP Memo/PFE-CVM/nº 965/08\nDe: PFE ...
565  RELATÓRIO\n1. Trata-se de proposta de Termo de...
609  RELATÓRIO\n1. Trata-se de proposta de Termo de...
664  RELATÓRIO\n1. Trata-se de proposta de Termo de...
665  RELATÓRIO\n1. Trata-se de proposta de Termo de...
666                                                NaN
691  RELATÓRIO\n1. Trata-se de proposta de Termo de...

In [93]:
df["identificador_lista_transformada"] = df["identificador_lista_transformada"].apply(ast.literal_eval)

In [94]:
df = df.explode("identificador_lista_transformada", ignore_index=True)

In [95]:
df["ID"] = df["identificador_lista_transformada"]

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 8 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ID                                699 non-null    object
 1   Texto                             699 non-null    object
 2   identificador_lista_transformada  699 non-null    object
 3   Escaneado                         699 non-null    bool
 4   Relatório                         663 non-null    object
 5   Relatório2                        438 non-null    object
 6   Relatório_final                   681 non-null    object
 7   len_rel                           673 non-null    float64
dtypes: bool(1), float64(1), object(6)
memory usage: 39.0+ KB

In [97]:
df = df.drop(columns=["Relatório", "Relatório2", "identificador_lista_transformada", "len_rel"])

In [98]:
df = df.rename(columns={"Relatório_final": "Relatório"})

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         699 non-null    object
 1   Texto      699 non-null    object
 2   Escaneado  699 non-null    bool
 3   Relatório  681 non-null    object
dtypes: bool(1), object(3)
memory usage: 17.2+ KB

In [99]:
df.to_csv("D:/Backup Tomas/T0mas/Faculdade/IC/Geral/Github CVM/corporate-fraud-in-brazil/data/interim/relatorios_dos_processos/relatorios_pctcs.csv", index=False)